### ISSUE TITLE
j.namespace @sort priority works flatly

### ISSUE THREAD

**Issue by bltzr** [jamoma/JamomaMax#534]
when sorting results by priority, j.namespace considers individual values of each of the results, and doesn't work recursively as it should (e.g. like j.cue does)

this can be seen in j.parameter.maxhelp

**Comment by lossius** [comment]
This is a problem with presents to j.model as well. I have changed the j.parameter help file substantially over the past few days, but in the Priority pane, the preset generated does not respect priorities, and if one extends this patch to trigger the default preset, it is not respected when being triggered either.

**Comment by lossius** [comment]
I consider this a sufficient important issue that I up the priority and move it to the 0.6 milestone.

**Comment by bltzr** [comment]
:+1:

**Comment by theod** [comment]
@bltzr, I have made several fixes around this so is it still an issue ?

**Comment by bltzr** [comment]
nope, doesn't work yet...
to reproduce:
- open j.parameter.maxhelp, open Priorities help
- open j.namespace.maxhelp
- press explore
-> starters comes after main_course after dessert....
(which is against any kind of culinary orthodoxy !!!!)

**Comment by bltzr** [comment]
I hadn't set @sort to priority... but when I do so, everything is scrambled in no definite order...
so maybe the problem comes from somewhere else...

**Comment by theod** [comment]
fixed !

**Comment by bltzr** [comment]
apparently (look at the Priorities tab in j.parameter.maxhelp), this still doesn't work with j.namespace (but it does work with presets) 
here's what j.namespace outputs: starter/soup, starter/salad, main_course/fish, main_course/vegetarian, dessert/cake, dessert/ice_cream, aaa, bbb, ccc_a, ccc_b, starter, main_course, dessert, model, preset, zzz
when it should be: aaa, bbb, ccc_a, ccc_b, starter,starter/soup, starter/salad, main_course, main_course/fish, main_course/vegetarian , dessert, dessert/cake, dessert/ice_cream, model, preset, zzz
I'm in 1.0.1 from Max's Package Manager
So, I'm reopening the issue....
